### ISSUE TITLE
What should we represent with lights

### ISSUE THREAD

**Issue by DuChenjunn** [ADIYuchengCai/DS4D-GROUP11#6]
What should we represent with lights, the oxygen emitted by the tree, or the carbon dioxide absorbed?

**Comment by ADIYuchengCai** [comment]
carbon dioxide abosorbed.

**Comment by ShulongZheng** [comment]
The lights are intended to represent the amount of carbon sequestered, and as this data is largely dependent on plant breath (photosynthesis), we use the breathing effect of the lights to represent this process, and the frequency of breathing will be linked to the carbon sequestration data.

**Comment by yolanda1908** [comment]
In terms of data, the ratio of oxygen absorbed to carbon dioxide emitted is essentially the same, so the difference cannot be reflected in the ratio. And since the oxygen produced by trees does not contribute significantly to the atmosphere, I tolerate that using the net absorption of carbon is the best

**Comment by YangReyna** [comment]
We can use light to represent tree breathing. Because the photosynthesis and transpiration of trees are invisible to people. We can use visualizations to show that trees are alive, just like people.
